# Generated by Django 5.1.6 on 2025-03-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(default='N/A')),
                ('education', models.TextField(default='N/A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
