# Generated by Django 5.2 on 2025-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
