# Generated by Django 5.2 on 2025-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0002_resume_email_resume_name_resume_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.JSONField(default=list),
        ),
    ]
