# Generated by Django 5.2 on 2025-04-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_matcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='job',
        ),
        migrations.RemoveField(
            model_name='match',
            name='resume',
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('apply_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('title', 'company', 'location')},
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
